version: '3.8'

services:
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_node
    networks:
      - ipfs_net
    volumes:
      - ./ipfs_staging:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"

networks:
  ipfs_net:
    driver: bridge

volumes:
  ipfs_staging:
    driver: local
  ipfs_data:
    driver: local

